spring.application.name=WeatherApplication
weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.forecast.url=http://api.weatherapi.com/v1/forecast.json
weather.api.key=60199ae4d2db45a7b92193613260703




